In [6]:
from scipy.optimize import fsolve
import numpy as np

# hotroom6H

In [7]:
# 3m tall block 
"""
# example
(
(0.3 0.3 4)    // 30% y-dir, 30% cells, expansion = 4
(0.35 0.4 1)    // 50% y-dir, 40% cells, expansion = 1
(0.35 0.3 0.25) // 20% y-dir, 30% cells, expansion = 0.25 (1/4)
)
"""

block_height = 3 #m 
splits = 2
percentages = [0.5, 0.5]


## boundary layer

In [8]:
U = 0.5 # m/s 
L = 20 # m (characteristic length)
nu = 1e-05 # dynamic viscosity
Re = U * L / nu
Re # 1e6

999999.9999999999

In [9]:
d99 = 0.38*L / (Re**(1/5))
d99 # 0.47 boundary layer thickness should be controlled here.., want yt = d99

0.4795275818049468

In [10]:
yh = 3.7e-2 # first layer height from other calculator TODO calc here 
N = 10 # based on empirical solution .., want y+ around 10

In [11]:
def growth(G):
    yh = 3.7e-2 
    yt = d99
    N = 10
    return yh * ((1 - G**N) / ( 1- G)) - yt
root = fsolve(growth, 3)
root # g should be this...

array([1.05640232])

In [12]:
# check
growth(root)

array([3.10862447e-15])

In [13]:
# check 
np.isclose(growth(root), [0.0])

array([ True])

## rest of mesh 

In [14]:
# yt is what percent of the distanc?
p_dist = d99/block_height
p_dist

0.1598425272683156

In [15]:
# number of cells in boundary layer is 10, it has 15% height, 15% cells maybe? 
tot_cells = N/p_dist
tot_cells

62.56157338662291

In [16]:
print((p_dist, p_dist, root))
(1 - p_dist, 1 - p_dist, 1)

(0.1598425272683156, 0.1598425272683156, array([1.05640232]))


(0.8401574727316844, 0.8401574727316844, 1)

In [17]:
70*63

4410

In [18]:
63*20

1260

In [19]:
# (0.16 0.16 g)    // 15% y-dir, 30% cells, expansion = 4
# (0.35 0.4 1)    // 50% y-dir, 40% cells, expansion = 1
()

()

In [20]:
# from online calc https://www.fluidmechanics101.com/pages/tools.html
# yh = 3.9e-3
# g = 1.06
# N= 10
# yh * ((1 - g**N) / ( 1- g)) 

In [21]:
10/50 # 0.2 cells in bl, 0.8 elsewhere 

0.2

In [22]:
# courant

In [23]:
min_face_area = 0.00699205
min_dist = np.sqrt(min_face_area)
min_dist

0.08361847881897876

In [24]:
C = U *1 /min_dist
C # high 

5.979539535542421

In [25]:
U * 0.1 /min_dist
# dt should be 0.1

0.5979539535542422

# hotRoom6I

In [26]:
d99 # m 

0.4795275818049468

In [28]:
# percentage d99 makes up of box
# actual 
# 50 cells, 20% in d99, 16% of total distance  
0.16 * block_height # 0.48 m , 48% of 1, 10 cells here 

0.48

In [ ]:
# for box, 48% of the 1 meter has 10 cells,
# 1 - 48% has 

In [29]:
# 40 cells in rest of the wt, which is 
3 - 0.48 # m 

2.52

In [30]:
2.52 / 40 # m per cell

0.063

In [31]:
(1 - 0.48) # meters left
# how many cells in 0.52 meters 

0.52

In [34]:
top_cells = 0.52 / 0.063 # (meters left / meters per cell)
# 8.23 cells

In [35]:
10/(10 + top_cells)

0.5478260869565218

In [36]:
1 - 0.548 

0.45199999999999996

In [ ]:
# 18 cells total, 1 meter tall block 


"""


            (0.16 0.2 1.06)    // % y-dir, % cells, expansion
            (0.84 0.8 1)    // % y-dir, % cells, expansion


            box
(0.48 0.548  1.06)
(0.48  0.452 1 )
"""

In [39]:
# in x, 20 m, 70 blocks 
20/80 # m per block 

0.25

In [38]:
# in z, 3 m, 20 blocks 
3/20 # m per block 

0.15